import { getClaimRecord, deleteClaimRecord } from '../lib/kv';

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

/**
 * GET /claim?token=xxx — fetch the license key generated by the webhook.
 * One-time retrieval: the claim is deleted after successful fetch.
 */
export function handleClaim(request: Request): Response {
  const url = new URL(request.url);
  const token = url.searchParams.get('token');

  if (!token) {
    return json({ error: 'Missing token parameter' }, 400);
  }

  const claim = getClaimRecord(token);
  if (!claim) {
    return json({ error: 'Claim not found or already used' }, 404);
  }

  // One-time use: delete after retrieval
  deleteClaimRecord(token);

  return json({
    license_key: claim.license_key,
    account_id: claim.account_id,
  });
}
